version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: "${RESTART}"
    ports:
      - ${WORDPRESS_PORT}:80
      - ${MYSQL_PORT}:3306/tcp
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${USERNAME}
      WORDPRESS_DB_PASSWORD: ${USERPASSWD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - wordpress:/var/www/html
  mysql:
    image: mysql:5.7
    restart: "${RESTART_DB}"
    ports :
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASSWD}
    volumes:
      - db:/var/lib/mysql
    network_mode: bridge
volumes:
  wordpress:
    driver: local
  db:
    driver: local
