version: "2"

services:
  elk:
    image: sebp/elk
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - MAX_MAP_COUNT=262144
    volumes:
      - elk-vol:/usr/share/elk/data
    ports:
      - ${KIBANA_PORT}:5601
      - ${ES_PORT}:9200
      - ${LS_PORT}:5044
    restart: "${RESTART}"

volumes:
  elk-vol:
    driver: local
